url=http://localhost:4200

############################################MongoDB#########################################################
spring.data.mongodb.uri=
spring.data.mongodb.database=
#############################################Email##########################################################
spring.mail.username=minerva.jjm@gmail.com
spring.mail.password=twmcuurblelifvud

kick.clientId=01JS7FQ6K1Y4KE79CB37SGE39T
kick.client.secret=b63940282f54d616ad315d5a958865f2f5e72b5eec97a3b63bdc1919774b3db2

google.clientId=819942257039-0ddspmh20hp67naooakhludghd14cror.apps.googleusercontent.com
youtube.api.key=AIzaSyBUkF5wvNoVghb8-3034b4i-QE3t3rRZb4
infura.api.key=
infura.api.secret=
encryption.key=kf5Wxc8)PXd}b*rLJ#N:p6Z<";Rvn'jzD
jwt.key=WnZr4u7x!z%C*F-JaNdRgUkXp2s5v8y/B?D(G+KbPeShVmYq3t6w9z$C&F)H@McQ
recaptcha.secret.key=6LdYbkIpAAAAADAOTM47L5KggqFjQEj6w6ItnpyW

contract.bid.address=
contract.channel.address=
contract.warchest.address=
contract.multiSend.address=
contract.interface.address=
contract.gaslessFunctionCall.address=
contract.testMana.address=

private.key.company=
private.key.one=
private.key.two=
private.key.three=
private.key.four=
private.key.five=
private.key.six=

